version: "2.3"

volumes:
  persist-redis:
  persist-mysql:

services:
  redstor:
    #image: redstor/redstor
    restart: always
    build:
      context: .
      target: redstor
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - '127.0.0.54:6379:6379'
    volumes:
      - ./:/app

  redis:
    image: redis:5
    restart: always
    ports:
      - '127.0.0.54:16379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - persist-redis:/data

  mysql:
    image: mariadb
    restart: always
    volumes:
      - persist-mysql:/var/lib/mysql
    ports:
      - '127.0.0.54:3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: z7L4evNETrmnRiU6x3am
      MYSQL_USER: redstor
      MYSQL_PASSWORD: m4&E3h9QTZ4FfqueZ^eN
      MYSQL_DATABASE: redstor