version: "2.3"

volumes:
  persist-redis:
  persist-mysql:

services:
  socat:
    image: alpine/socat
    command: tcp-listen:6379,fork,reuseaddr tcp-connect:redstor:6379
    ports:
      - '127.0.0.54:6379:6379'
    depends_on:
      redstor:
        condition: service_healthy

  redstor:
    #image: redstor/redstor
    restart: always
    scale: 1
    build:
      context: .
      target: redstor
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
    environment:
      REDIS_HOST: tcp://redis:6379
      MYSQL_HOST: tcp://redstor:m4&E3h9QTZ4FfqueZ^eN@mysql:3306

  gateway:
    restart: always
    build:
      context: .
      target: gateway
    depends_on:
      redstor:
        condition: service_healthy
    volumes:
      - ./:/app
    environment:
      REDSTOR_HOST: tcp://redstor:6379
      REDIS_HOST: tcp://redstor:6379
    ports:
      - '127.0.0.54:80:80'

  redis:
    image: benzine/redis:5
    restart: always
    ports:
      - '127.0.0.54:16379:6379'
    volumes:
      - persist-redis:/data

  mysql:
    image: benzine/mariadb:10.4
    restart: always
    volumes:
      - persist-mysql:/var/lib/mysql
    ports:
      - '127.0.0.54:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: z7L4evNETrmnRiU6x3am
      MYSQL_USER: redstor
      MYSQL_PASSWORD: m4&E3h9QTZ4FfqueZ^eN
      MYSQL_DATABASE: redstor

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.54:8081:8081"