name: RedStor CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Composer Install
      uses: MilesChou/composer-action@master
    - name: PHPUnit Tests
      uses: MilesChou/composer-action@master

